### ISSUE TITLE
Person joining

### ISSUE THREAD

**Issue by bill88t** [Maartii/Jester#1]
If a person joins after the start button is pressed the entire plugin bugs out.

**Comment by Maartii** [comment]
Thanks for opening an issue here! 

What do you see when a person joins after the start button? When I tried to reproduce it I found that one player gets a message that they will 'be jester (unless they'll be impostor)', but they (likely) never become jester after that. That on itself is a bug that would be good to fix, so will try to do that soon. Does anything else happen for you when someone joins after clicking the start button?

**Comment by bill88t** [comment]
Start button is pressed
OPEN CHAT is visible
person joins
Start button is pressed
we eject the jester #1
Hats appear game doesn't end
we eject jester #2
hats don't appear game continues
we eject impostor
chat says jester won
plugin won't end any games until we make a new lobby

**Comment by Maartii** [comment]
Thanks for the explanation. Not entirely sure what's causing it, but will try to fix it as soon as possible.

**Comment by Maartii** [comment]
@bill88t 

Tried to fix this in the new version. Could you maybe try to use the new version of the plugin (1.1.1) with the latest **experimental** version of the Impostor server? (current version is 1.2.2-ci.123, you can find it at https://ci.appveyor.com/project/Impostor/Impostor/branch/dev/artifacts)

As of now, it still doesn't work when you press start again while 'OPEN CHAT' is still visible. But if you press the start button after that it should (hopefully) be fine, let me know how it goes.

**Comment by bill88t** [comment]
Sure, me and my friends will most likely gather tonight. We will play it.
