### ISSUE TITLE
Jester is not working correctly

### ISSUE THREAD

**Issue by Ougawa** [Maartii/Jester#2]
Hello !
I've tried your mod with a bunch of friends, we managed to make it working but it seems like Jester can't win the game.
We tested multiple games to try if we can make him win. When he is being voted during an emergency, the game still continue.
In the console, we can see that "Jester has won"
https://cdn.discordapp.com/attachments/772170650898923584/788542838878896148/unknown.png
But the game doesn't stop, and no matter what we're doing (finishing all tasks, voting imposter, or imposter killing everyone) there is no way where we have the Jester screen at the end.

I supposed that you wanted to end the game when Jester wins, but for me and my group it's not working at all.
Is there a solution for it,
Thank you

**Comment by Maartii** [comment]
Thanks for opening an issue here! 

Something strange is going one here, and I'm not entirely sure yet what, since for me it works fine somehow. I'll try to fix it as soon as possible though.

**Comment by Ougawa** [comment]
Is there a way for me to give you informations to help you find what's the problem?
It's pretty weird if that works for you and not for us. I mean, we just added the mod on the plugin folder of Impostor, i don't think there is anything else to do for the mod to work? (We've put last version of Impostor and we've tried 2 different releases of your Jester mod)

**Comment by celsosa** [comment]
Same problem here, tested on 1.0.1 and 1.1.0 :/

**Comment by Maartii** [comment]
@Ougawa @celsosa 
Tried to fix the issue. Could you maybe try to use the new version of the plugin (1.1.1) with the latest **experimental** version of the Impostor server? (current version is 1.2.2-ci.123, you can find it at https://ci.appveyor.com/project/Impostor/Impostor/branch/dev/artifacts)

Hope everything will be running smoothly for you now, please let me know how it goes if you decide to try it.

**Comment by Maartii** [comment]
@Ougawa 

Your way of installing the mod was correct by the way, you only have to drop it into the plugin folder of Impostor.

**Comment by RobinRMC** [comment]
Same issue for me.

**Comment by Ougawa** [comment]
I'm gonna try soon as i can your fix Maartii.


> Same issue for me.

Did you try his fix he sent me ?

**Comment by Maartii** [comment]
@RobinRMC 
Just to verify, were you using the new version of the plugin with the latest experimental build of the Impostor server?

**Comment by Ougawa** [comment]
I've just tried with my group, and seems like it's working now!
I'm gonna send you more if i see some bugs

**Comment by Maartii** [comment]
Thanks, good to know! Happy to hear it works now. Would be glad to hear if there are any bugs.

**Comment by celsosa** [comment]
> @Ougawa @celsosa
> Tried to fix the issue. Could you maybe try to use the new version of the plugin (1.1.1) with the latest **experimental** version of the Impostor server? (current version is 1.2.2-ci.123, you can find it at https://ci.appveyor.com/project/Impostor/Impostor/branch/dev/artifacts)
> 
> Hope everything will be running smoothly for you now, please let me know how it goes if you decide to try it.

Now it works, thanks ^-^ (btw, did u update the source code? Cause I want to compile the plugin translatade, so my friends can understand the game mode )

**Comment by Maartii** [comment]
> Now it works, thanks ^-^ (btw, did u update the source code? Cause I want to compile the plugin translatade, so my friends can understand the game mode )

Glad to hear it works. Yep, I updated the source code as well. Good luck!
